### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by ghost** [noah-dennis-dev/AdventOfCode2023#1]
# This is devastating

You clearly copied @joel-heath 's 2022 Advent of Code repo.

Unacceptable.

**Comment by ghost** [comment]
That is, this repo https://github.com/joel-heath/AdventOfCode2022

**Comment by noah-dennis-dev** [comment]
You see @22jh0369, whilst it is true I have taken inspiration from the README file of the repo you refer to, it is not copied as the content has been changed.

Inspired, not duplicated.

**Comment by ghost** [comment]
> You see @22jh0369, whilst it is true I have taken inspiration from the README file of the repo you refer to, it is not copied as the content has been changed.

erm, sorry but i just aksked chat PGT if he generatwed that and he said YES. Sorry, your AI is too PREDICTABLE.

> Inspired, not duplicated.

And FYI, that is a falsehood. I watched you do it

**Comment by noah-dennis-dev** [comment]
Sorry you feel this way. If you don't believe the truth then we will have many issues.
Just remember the truth will set you free. Maybe try reading John 8:31-32 and see what it has to say.
